apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: hello-go
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
