apiVersion: v1
kind: Pod
metadata:
  name: ubuntu18-base-t
  labels:
    env: ubuntu18-base
spec:
  containers:
  - name: ubuntu18-base2
    image: ubuntu:18.04
    securityContext:
      privileged: true
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 11;done"]
